### ISSUE TITLE
Change 'start' function

### ISSUE THREAD

**Issue by rocketinventor** [c9/c9.ide.preview.browser#2]
In the preview, one of the injected scripts overrides the public `start` function. This breaks functionality when the HTML being previewed _also_ has a function in it's JS called `start`. This problem source is not very obvious when it happens and can cause lots of potential frustration when developing.

This function should either be renamed, or made private. An easy way to fix this would be to add underscores before and after to make it a "private" function (convention equivalent). Suggestions for easy variable rename with low chance of conflict: `__start__`, `_start_`, `start__2`, `__start`, and `liveCodeStart`.

**Comment by rocketinventor** [comment]
@nightwing Has this been fixed?

**Comment by nightwing** [comment]
it was fixed by https://github.com/c9/c9.ide.preview.browser/commit/1de1b699c857aa7d57ae8b0f4c29e5559df0b04d and https://github.com/c9/core/commit/e8893951a7dc8a567f41e53dbec4c9c6557056b6

But it is not deployed to c9.io yet

**Comment by rocketinventor** [comment]
Ah, that looks much better!
What does the deploy schedule look like for c9.io?
